# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Form.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_Main_Form(object):
    def setupUi(self, form_Main_Form):
        form_Main_Form.setObjectName("form_Main_Form")
        form_Main_Form.resize(570, 550)
        self.centralwidget = QtWidgets.QWidget(form_Main_Form)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 571, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Table = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Table.setContentsMargins(0, 0, 0, 0)
        self.Table.setObjectName("Table")

        self.Newcode = QtWidgets.QGridLayout()
        self.Newcode.setObjectName("NewCode")
        self.Table.addLayout(self.Newcode, 0, 0, 0, 0)

        form_Main_Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(form_Main_Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        form_Main_Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(form_Main_Form)
        self.statusbar.setObjectName("statusbar")
        form_Main_Form.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(form_Main_Form)
        self.toolBar.setObjectName("toolBar")
        form_Main_Form.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.fileSave = QtWidgets.QAction(form_Main_Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileSave.setIcon(icon)
        self.fileSave.setObjectName("fileSave")
        self.Save_as = QtWidgets.QAction(form_Main_Form)
        self.Save_as.setObjectName("Save_as")
        self.About = QtWidgets.QAction(form_Main_Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/about.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.About.setIcon(icon1)
        self.About.setObjectName("About")
        self.change = QtWidgets.QAction(form_Main_Form)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/change.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.change.setIcon(icon2)
        self.change.setObjectName("change")
        self.New = QtWidgets.QAction(form_Main_Form)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/userNew.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("res/mimaNew.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.New.setIcon(icon3)
        self.New.setObjectName("New")
        self.new_user = QtWidgets.QAction(form_Main_Form)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/new_user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.new_user.setIcon(icon4)
        self.new_user.setObjectName("new_user")
        self.fileOpen = QtWidgets.QAction(form_Main_Form)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res/fileOpen.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.fileOpen.setIcon(icon5)
        self.fileOpen.setObjectName("fileOpen")
        self.menu.addAction(self.fileOpen)
        self.menu.addAction(self.fileSave)
        self.menu.addAction(self.Save_as)
        self.menu.addAction(self.change)
        self.menu_2.addAction(self.new_user)
        self.menu_2.addAction(self.New)
        self.menu_3.addAction(self.About)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.toolBar.addAction(self.fileOpen)
        self.toolBar.addAction(self.fileSave)
        self.toolBar.addAction(self.new_user)
        self.toolBar.addAction(self.New)
        self.toolBar.addAction(self.About)

        self.retranslateUi(form_Main_Form)
        QtCore.QMetaObject.connectSlotsByName(form_Main_Form)

    def retranslateUi(self, form_Main_Form):
        _translate = QtCore.QCoreApplication.translate
        form_Main_Form.setWindowTitle(_translate("form_Main_Form", "MainWindow"))
        self.menu.setTitle(_translate("form_Main_Form", "文件"))
        self.menu_2.setTitle(_translate("form_Main_Form", "编辑"))
        self.menu_3.setTitle(_translate("form_Main_Form", "帮助"))
        self.toolBar.setWindowTitle(_translate("form_Main_Form", "toolBar"))
        self.fileSave.setText(_translate("form_Main_Form", "保存...           Ctrl+S"))
        self.fileSave.setShortcut(_translate("form_Main_Form", "Ctrl+S"))
        self.Save_as.setText(_translate("form_Main_Form", "另存为..."))
        self.Save_as.setToolTip(_translate("form_Main_Form", "另存为"))
        self.About.setText(_translate("form_Main_Form", "关于本产品"))
        self.About.setToolTip(_translate("form_Main_Form", "关于本产品"))
        self.change.setText(_translate("form_Main_Form", "更改登录密码"))
        self.change.setToolTip(_translate("form_Main_Form", "更改登录密吗"))
        self.New.setText(_translate("form_Main_Form", "新建密码"))
        self.New.setToolTip(_translate("form_Main_Form", "新建密码"))
        self.new_user.setText(_translate("form_Main_Form", "新用户          Ctrl+N"))
        self.new_user.setToolTip(_translate("form_Main_Form", "新用户"))
        self.new_user.setShortcut(_translate("form_Main_Form", "Ctrl+N"))
        self.fileOpen.setText(_translate("form_Main_Form", "打开...           Ctrl+O"))
        self.fileOpen.setToolTip(_translate("form_Main_Form", "打开..."))
        self.fileOpen.setShortcut(_translate("form_Main_Form", "Ctrl+O"))

