# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Form.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_Main_Form(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 551)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 180, 460))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.treeView = QtWidgets.QTreeView(self.layoutWidget)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 25))

        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.New = QtWidgets.QAction(MainWindow)
        self.New.setCheckable(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/New.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.New.setIcon(icon)
        self.New.setObjectName("New")
        self.fileSave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.fileSave.setIcon(icon1)
        self.fileSave.setObjectName("fileSave")
        self.Save_as = QtWidgets.QAction(MainWindow)
        self.Save_as.setObjectName("Save as")
        self.About = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/about.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.About.setIcon(icon2)
        self.About.setObjectName("About")
        self.change = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/change.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.change.setIcon(icon3)
        self.change.setObjectName("change")
        self.new_2 = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/userNew.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap("res/mimaNew.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.new_2.setIcon(icon4)
        self.new_2.setObjectName("new_2")
        self.new_user = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res/new_user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.new_user.setIcon(icon5)
        self.new_user.setObjectName("new_user")
        self.fileOpen = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("res/fileOpen.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.fileOpen.setIcon(icon6)
        self.fileOpen.setObjectName("fileOpen")
        self.menu.addAction(self.fileOpen)
        self.menu.addAction(self.new_user)
        self.menu.addAction(self.fileSave)
        self.menu.addAction(self.Save_as)
        self.menu.addAction(self.change)
        self.menu_2.addAction(self.New)
        self.menu_2.addAction(self.new_2)
        self.menu_3.addAction(self.About)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.toolBar.addAction(self.fileOpen)
        self.toolBar.addAction(self.fileSave)
        self.toolBar.addAction(self.new_user)
        self.toolBar.addAction(self.New)
        self.toolBar.addAction(self.new_2)
        self.toolBar.addAction(self.About)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.New.setText(_translate("MainWindow", "新建分组"))
        self.New.setToolTip(_translate("MainWindow", "新建分组"))
        self.fileSave.setText(_translate("MainWindow", "保存...           Ctrl+S"))
        self.fileSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.Save_as.setText(_translate("MainWindow", "另存为..."))
        self.Save_as.setToolTip(_translate("MainWindow", "另存为"))
        self.About.setText(_translate("MainWindow", "关于本产品"))
        self.About.setToolTip(_translate("MainWindow", "关于本产品"))
        self.change.setText(_translate("MainWindow", "更改登录密码"))
        self.change.setToolTip(_translate("MainWindow", "更改登录密吗"))
        self.new_2.setText(_translate("MainWindow", "新建密码"))
        self.new_2.setToolTip(_translate("MainWindow", "新建密码"))
        self.new_user.setText(_translate("MainWindow", "新用户          Ctrl+N"))
        self.new_user.setToolTip(_translate("MainWindow", "新用户"))
        self.new_user.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.fileOpen.setText(_translate("MainWindow", "打开...           Ctrl+O"))
        self.fileOpen.setToolTip(_translate("MainWindow", "打开..."))
        self.fileOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))

